services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
    depends_on:
      - db
    networks:
      - application
    command: php artisan serve --host=0.0.0.0 --port=8000  
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_library
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - application
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5  

volumes:
  db_data:

networks:
  application:
    driver: bridge